### ISSUE TITLE
Not adding to MadMimi list

### ISSUE THREAD

**Issue by julie-lunarwp** [katzwebservices/Gravity-Forms-Mad-Mimi#2]
GF v 1.7.11
MadMimi v2.0 (as both Beta and Stable installed - why? with only Stable activated)
WordPress v3.7

For the past week to 10 days, our MadMimi list has not received the subscription entries (they are captured in GF entries and we just added them manually).  I did an upgrade sometime within that timeframe.

Ideas?

**Comment by zackkatz** [comment]
This should be fixed in 2.0.1 - sorry for the problems.
