### ISSUE TITLE
Mad Mimi isn't showing up under Forms in the Admin area

### ISSUE THREAD

**Issue by Neal-Ghoshal** [katzwebservices/Gravity-Forms-Mad-Mimi#3]
Hi there,

I've used this plugin before and it works well. But on a new installation, I've installed the plugin and Gravity Forms, connected it up the Mad Mimi account under settings, but it's not possible to add a feed because there is not a Mad Mimi link under Forms in the admin area - can you help? Thanks!

**Comment by Neal-Ghoshal** [comment]
Fixed this ... interestingly when I install the Mad Mimi Gravity Forms Wordpress plugin - it loads two versions, one beta and one stable and it's important to have the stable one active!

**Comment by zackkatz** [comment]
The Beta version of the plugin is under Form > Settings > Mad Mimi instead of having the link in the sidebar.
