### ISSUE TITLE
Not adding to MadMimi List

### ISSUE THREAD

**Issue by bcapphoto** [katzwebservices/Gravity-Forms-Mad-Mimi#5]
Any idea why my Gravity Forms forms aren't adding to my MadMimi list? Seems like the feed is all set up a-ok and the form "submits" ok.

**Comment by ryankoral** [comment]
i'm in the same boat.  the submit/thank-you screen is blank - but i'm receiving an email that it says it worked.  but it's not adding to the madmimi list either...

**Comment by JamesDDunn** [comment]
I've had this issue before. The simplest way I've found to solve it is to create a Webform in MadMimi for the list you are trying to add to and it usually works perfectly. I've also discovered tonight that MadMimi only allows ONE WebForm if you're using their FREE account - that's a recent change.

**Comment by JamesDDunn** [comment]
Ignore my previous comment. It is apparently a problem with paid or free accounts and the trick I used before with the web forms no longer works either. There was something changed about October 2013 that has caused the system to fall apart.

**Comment by zackkatz** [comment]
This should be fixed in version 2.0.1. Sorry for the issues.
