### ISSUE TITLE
When will the beta plugin disappear?

### ISSUE THREAD

**Issue by gitlappi** [katzwebservices/Gravity-Forms-Mad-Mimi#7]
Your plugin installs two versions - and one of them is beta. I keep getting messages from my hosting provider that I should not have inactive plugins. 

When will you update the plugin - or at least give the chance to delete the inactive version?

**Comment by zackkatz** [comment]
Their security concerns aren't relevant for two plugins updated from a single source plugin. Don't worry about their warnings in this case.

The beta will stick around for a bit, probably 6 months or so.
